name: Issue
identifier: uuid
features:
  displayNumber: true
  status: true
  priority: true
  assets: true
  orgSync: true
  move: true
  duplicate: true
statuses:
  - open
  - planning
  - in-progress
  - closed
  - Not wanted
defaultStatus: open
priorityLevels: 3
